jenkins:
  systemMessage: >-
    This jenkins is managed by configuration as code, update <a
    href="https://github.com/hmcts/cnp-jenkins-config/blob/master/cac-prod.yml">here</a>
  globalNodeProperties:
    - envVars:
        env:
          - key: INFRA_VAULT_NAME
            value: infra-vault-prod
          - key: JAVA_OPTS
            value: -Xmx2g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
          - key: GRADLE_OPTS
            value: -Xmx2g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
          - key: REGISTRY_NAME
            value: hmcts
          - key: AAT_AKS_CLUSTER_NAME
            value: aat-00-aks
          - key: AAT_AKS_RESOURCE_GROUP
            value: aat-00-rg
          - key: PREVIEW_AKS_CLUSTER_NAME
            value : cnp-aks-cluster
          - key : PREVIEW_AKS_RESOURCE_GROUP
            value: cnp-aks-rg
          - key: AKS_PREVIEW_SUBSCRIPTION_NAME
            value: DCD-CNP-DEV
          - key: AKS_AAT_SUBSCRIPTION_NAME
            value: DCD-CFTAPPS-STG
          - key : AAT_AKS_KEY_VAULT
            value: cftapps-stg
  markupFormatter:
    rawHtml:
      disableSyntaxHighlighting: false
  numExecutors: 0
  primaryView:
    all:
      name: all
  views:
    - all:
        name: all
    - buildMonitor:
        includeRegex: >-
          ^HMCTS_.*(Platform|CNP).*\/(draft-store|rpe-pdf-service|feature-toggle-api|private-beta-invitation-service|service-auth-provider-app|spring-boot-template|cnp-rhubarb-recipes-service|cnp-plum-recipes-service|cnp-plum-frontend|cnp-plum-shared-infrastructure)\/master
        name: Platform
        recurse: true
        title: Platform
    - buildMonitor:
        includeRegex: >-
          ^HMCTS_.*Platform.*\/(bulk-scan-.*|send-letter-service)\/master
        name: BSP
        recurse: true
        title: BSP
    - buildMonitor:
        includeRegex: >-
          .+\/(prd-.*)\/(master|demo)
        name: PRD
        recurse: true
        title: PRD
    - buildMonitor:
        includeRegex: >-
          .+\/(prd-.*)\/(.*PR-.*)
        name: PRD-PR
        recurse: true
        title: PRD-PR
    - buildMonitor:
        includeRegex: >-
          .+\/(rpa-.*)\/(master|demo)
        name: RPA
        recurse: true
        title: RPA
    - buildMonitor:
        includeRegex: >-
          .+\/(rpa-.*)\/(.*PR-.*)
        name: RPA-PR
        recurse: true
        title: RPA-PR
    - buildMonitor:
        includeRegex: >-
          .+\/(rpx-.*)\/(master|demo)
        name: RPX
        recurse: true
        title: RPX
    - buildMonitor:
        includeRegex: >-
          .+\/(rpx-.*)\/(.*PR-.*)
        name: RPX-PR
        recurse: true
        title: RPX-PR
    - buildMonitor:
        includeRegex: >-
          HMCTS_CDM.+\/master
        name: CDM
        recurse: true
        title: CDM master Builds
    - buildMonitor:
        includeRegex: >-
          HMCTS_CDM.+\/demo
        name: CDM demo
        recurse: true
        title: CDM demo Builds
    - buildMonitor:
        includeRegex: >-
          HMCTS_Nightly_CDM.+\/master
        name: CDM Nightly
        recurse: true
        title: CDM Nightly Builds
    - buildMonitor:
        includeRegex: >-
          ^HMCTS_.*SSCS.*\/(sscs-evidence-share|sscs-bulk-scan|sscs-case-loader|sscs-cor-backend|sscs-cor-frontend|sscs-shared-infrastructure|sscs-submit-your-appeal|sscs-track-your-appeal-frontend|sscs-track-your-appeal-notifications|sscs-tribunals-case-api|sscs-ccd-e2e-tests)\/master
        name: SSCS
        recurse: true
        title: SSCS Dashboard
    - buildMonitor:
        includeRegex: >-
          ^HMCTS_.*IAC.*\/.+\/master
        name: IA
        recurse: true
        title: I & A Dashboard
    - buildMonitor:
        includeRegex: >-
          ^HMCTS_.*Probate.*\/(probate-frontend|probate-persistence-service|probate-business-service|probate-submit-service|probate-back-office)\/(master|demo|cnp)
        name: PROBATE
        recurse: true
        title: PROBATE Dashboard
    - buildMonitor:
        includeRegex: >-
          ^HMCTS_.*Intestacy.*\/(intestacy-frontend|intestacy-orchestrator-service)\/(master|demo|cnp)
        name: INTESTACY
        recurse: true
        title: INTESTACY Dashboard
    - buildMonitor:
        includeRegex: >-
          HMCTS_DIV/(?!div-ansible|div-case-progression-service|div-feature-toggle-client|div-frontend-boilerplate).+\/master
        name: DIV
        recurse: true
        title: Divorce Dashboard
    - buildMonitor:
        includeRegex: >-
          .+\/(am-.*)\/(master|demo)
        name: AM
        recurse: true
        title: AM
    - buildMonitor:
        includeRegex: >-
          .+\/(am-.*)\/(.*PR-.*)
        name: AM-PR
        recurse: true
        title: AM-PR
    - buildMonitor:
        includeRegex: >-
          HMCTS_.*CTSC\/.+\/master
        name: CTSC
        recurse: true
        title: CTSC
    - buildMonitor:
        includeRegex: >-
          HMCTS_.*ETHOS\/.+\/master
        name: ETHOS
        recurse: true
        title: ETHOS
    - buildMonitor:
        includeRegex: >-
          ^HMCTS_.*(CMC).*\/(cmc-citizen-frontend|cmc-legal-rep-frontend|cmc-claim-store|cmc-shared-infrastructure)\/master
        name: CMC
        recurse: true
        title: CMC
    - buildMonitor:
        includeRegex: >-
          ^HMCTS_.*RD.*\/.+\/master
        name: RD
        recurse: true
        title: Ref Data Dashboard
  authorizationStrategy:
    globalMatrix:
      grantedPermissions:
        - "Overall/Administer:300e771f-856c-45cc-b899-40d78281e9c1"
        - "Overall/Administer:c36eaede-a0ae-4967-8fed-0a02960b1370"
        - "Overall/Read:authenticated"
        - "View/Read:authenticated"
        - "View/Configure:authenticated"
        - "Run/Replay:authenticated"
        - "Run/Update:authenticated"
        - "Job/Configure:authenticated"
        - "Job/Cancel:authenticated"
        - "Job/Read:authenticated"
        - "Job/Build:authenticated"
        - "Job/Move:authenticated"
        - "Job/Discover:authenticated"
        - "Job/Discover:anonymous"
        - "Job/Workspace:authenticated"
        - "Credentials/View:authenticated"
        - "Build Failure Analyzer/RemoveCause:authenticated"
        - "Build Failure Analyzer/UpdateCauses:authenticated"
        - "Build Failure Analyzer/ViewCauses:authenticated"
        - "Lockable Resources/Unlock:authenticated"
        - "Lockable Resources/Reserve:authenticated"
        - "SCM/Tag:authenticated"

  securityRealm:
    saml:
      binding: "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect"
      displayNameAttributeName: "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name"
      groupsAttributeName: "http://schemas.microsoft.com/ws/2008/06/identity/claims/groups"
      idpMetadataConfiguration:
        period: 15
        url: "https://login.microsoftonline.com/hmcts.net/FederationMetadata/2007-06/FederationMetadata.xml"
      maximumAuthenticationLifetime: 1209600
      usernameAttributeName: "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name"
      usernameCaseConversion: "none"
  clouds:
    - azureVM:
        azureCredentialsId: "jenkinsServicePrincipal"
        cloudName: "cnp-azure"
        deploymentTimeout: 1200
        existingResourceGroupName: "mgmt-vmimg-store-prod"
        maxVirtualMachinesLimit: 60
        resourceGroupReferenceType: "existing"
        vmTemplates:
        - agentLaunchMethod: "SSH"
          agentWorkspace: "/opt/jenkins"
          builtInImage: "Windows Server 2016"
          credentialsId: "vm_agent_creds"
          diskType: "managed"
          doNotUseMachineIfInitFails: true
          enableMSI: false
          enableUAMI: false
          executeInitScriptAsRoot: true
          existingStorageAccountName: "mgmtvmimgstoreprod"
          imageReference:
            id: "/subscriptions/8999dec3-0104-4a27-94ee-6588559729d1/resourceGroups/cnp-vmimages-prod/providers/Microsoft.Compute/images/moj-centos-agent74-20190415141712"
          imageTopLevelType: "advanced"
          initScript: |-
            usermod -a -G docker jenkinsssh
            umount /mnt/resource
            mkdir -pv /opt/jenkins
            mount /dev/sdc1 /opt/jenkins
            chown -R jenkinsssh:jenkinsssh /opt/jenkins
            mv /tmp/jenkinsssh_id_rsa /home/jenkinsssh/.ssh/id_rsa
            chown jenkinsssh:jenkinsssh /home/jenkinsssh/.ssh/id_rsa
            chmod 0600 /home/jenkinsssh/.ssh/id_rsa
            mv /tmp/vault-token /home/jenkinsssh/.vault-token
            chown -R jenkinsssh:jenkinsssh /home/jenkinsssh/.vault-token
            chmod 0600 /home/jenkinsssh/.vault-token
            mkdir /opt/jenkins/.gradle && echo 'org.gradle.daemon=false' >/opt/jenkins/.gradle/gradle.properties
            cat > /etc/dnsmasq.d/10-internal-forwarding<<EOF
            server=/#/10.96.4.10
            EOF
            systemctl restart dnsmasq
            cat >/etc/security/limits.d/30-jenkins.conf<<EOF
            jenkinsssh soft nofile 40960
            jenkinsssh hard nofile 40960
            jenkinsssh soft nproc 32768
            jenkinsssh hard nproc 32768
            EOF
            ssh-keyscan github.com github.com >> /home/jenkinsssh/.ssh/known_hosts
            ssh-keygen -F github.com -f /home/jenkinsssh/.ssh/known_hosts # verifies key is correctly installed
          installDocker: false
          installGit: false
          installMaven: false
          jvmOptions: "-Xms4G -Xmx4G -XX:+UseG1GC -XX:+UseCompressedOops -XX:+UseCompressedClassPointers\
            \ -XX:+AlwaysPreTouch -XX:+UseStringDeduplication -XX:+ParallelRefProcEnabled\
            \ -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:+UnlockDiagnosticVMOptions\
            \ -XX:G1SummarizeRSetStatsPeriod=1 "
          location: "UK South"
          noOfParallelJobs: 1
          osDiskSize: 50
          osType: "Linux"
          preInstallSsh: true
          retentionStrategy:
            azureVMCloudRetentionStrategy:
              idleTerminationMinutes: 60
          shutdownOnIdle: false
          storageAccountNameReferenceType: "existing"
          storageAccountType: "Standard_LRS"
          subnetName: "jenkins-subnet"
          templateDesc: "Jenkins build agents for HMCTS"
          templateDisabled: false
          templateName: "cnp-jenkins-builders"
          templateStatusDetails: "The provided Image ID does not exist"
          usageMode: "Use this node as much as possible"
          usePrivateIP: true
          virtualMachineSize: "Standard_D4_v3"
          virtualNetworkName: "mgmt-infra-prod"
          virtualNetworkResourceGroupName: "mgmt-infra-prod"
jobs:
  - url: https://raw.githubusercontent.com/hmcts/cnp-jenkins-config/master/jobdsl/organisations.groovy

unclassified:
  location:
    adminAddress: jenkins-reform@hmcts.net
    url: 'https://build.platform.hmcts.net'
  globalLibraries:
    libraries:
      - name: 'Infrastructure'
        includeInChangesets: false
        defaultVersion: master
        retriever:
          modernSCM:
            scm:
              github:
                credentialsId: jenkins-github-hmcts-api-token
                repoOwner: hmcts
                repository: cnp-jenkins-library
      - name: 'Pipeline'
        includeInChangesets: false
        defaultVersion: master
        retriever:
          modernSCM:
            scm:
              github:
                credentialsId: jenkins-github-hmcts-api-token
                repoOwner: hmcts
                repository: cnp-jenkins-library
  slackNotifier:
    teamDomain: hmcts-reform
    tokenCredentialId: slack-token
  githubpluginconfig:
    configs:
      - name: "GitHub"
        apiUrl: "https://api.github.com"
        credentialsId: "jenkins-github-hmcts-api-token"
        manageHooks: false
  azureKeyVault:
    keyVaultURL: https://infra-vault-prod.vault.azure.net
    credentialID: jenkinsServicePrincipal
  timestamperConfig:
    allPipelines: true
