jenkins:
  systemMessage: >-
    This jenkins is managed by configuration as code, update <a
    href="https://github.com/hmcts/cnp-jenkins-config/blob/master/cac-prod.yml">here</a>
  markupFormatter:
    rawHtml:
      disableSyntaxHighlighting: false
  primaryView:
    all:
      name: all
  views:
    - all:
        name: all
    - buildMonitor:
        includeRegex: >-
          ^HMCTS_.*(Platform|CNP).*\/(draft-store|cmc-pdf-service|feature-toggle-api|private-beta-invitation-service|service-auth-provider-app|spring-boot-template|cnp-rhubarb-recipes-service)\/master
        name: Platform
        recurse: true
        title: Platform
    - buildMonitor:
        includeRegex: >-
          ^HMCTS_.*Platform.*\/(bulk-scan-.*|send-letter-service)\/master
        name: BSP
        recurse: true
        title: BSP
    - buildMonitor:
        includeRegex: >-
          .+\/(rpa-.*)\/(master|demo)
        name: RPA
        recurse: true
        title: RPA
    - buildMonitor:
        includeRegex: >-
          .+\/(rpa-.*)\/(.*PR-.*)
        name: RPA-PR
        recurse: true
        title: RPA-PR
    - buildMonitor:
        includeRegex: >-
          HMCTS_CDM.+\/master
        name: CDM
        recurse: true
        title: CDM master Builds
    - buildMonitor:
        includeRegex: >-
          HMCTS_Nightly_CDM.+\/master
        name: CDM Nightly
        recurse: true
        title: CDM Nightly Builds
    - buildMonitor:
        includeRegex: >-
          ^HMCTS_.*SSCS.*\/(sscs-bulk-scan|sscs-case-loader|sscs-cor-backend|sscs-cor-frontend|sscs-shared-infrastructure|sscs-submit-your-appeal|sscs-track-your-appeal-frontend|sscs-track-your-appeal-notifications|sscs-tribunals-case-api|sscs-ccd-e2e-tests)\/master
        name: SSCS
        recurse: true
        title: SSCS Dashboard
    - buildMonitor:
        includeRegex: >-
          ^HMCTS_.*IAC.*\/(ia-case-api|ia-shared-infrastructure|ia-ccd-e2e-tests)\/master
        name: IA
        recurse: true
        title: I & A Dashboard
    - buildMonitor:
        includeRegex: >-
          ^HMCTS_.*Probate.*\/(probate-frontend|probate-persistence-service|probate-business-service|probate-submit-service|probate-back-office)\/(master|demo|cnp)
        name: PROBATE
        recurse: true
        title: PROBATE Dashboard
    - buildMonitor:
        includeRegex: >-
          ^HMCTS_.*Intestacy.*\/(intestacy-frontend|intestacy-orchestrator-service)\/(master|demo|cnp)
        name: INTESTACY
        recurse: true
        title: INTESTACY Dashboard
    - buildMonitor:
        includeRegex: >-
          HMCTS_DIV/(?!div-ansible|div-case-progression-service|div-feature-toggle-client|div-frontend-boilerplate).+\/master
        name: DIV
        recurse: true
        title: Divorce Dashboard
    - buildMonitor:
        includeRegex: >-
          .+\/(am-.*)\/(master|demo)
        name: AM
        recurse: true
        title: AM
    - buildMonitor:
        includeRegex: >-
          .+\/(am-.*)\/(.*PR-.*)
        name: AM-PR
        recurse: true
        title: AM-PR
    - buildMonitor:
        includeRegex: >-
          HMCTS_.*CTSC\/.+\/master
        name: CTSC
        recurse: true
        title: CTSC
  authorizationStrategy:
    globalMatrix:
      grantedPermissions:
        - "Overall/Administer:300e771f-856c-45cc-b899-40d78281e9c1"
        - "Overall/Read:authenticated"
        - "View/Read:authenticated"
        - "View/Configure:authenticated"
        - "Run/Replay:authenticated"
        - "Run/Update:authenticated"
        - "Job/Configure:authenticated"
        - "Job/Cancel:authenticated"
        - "Job/Read:authenticated"
        - "Job/Build:authenticated"
        - "Job/Move:authenticated"
        - "Job/Discover:authenticated"
        - "Job/Discover:anonymous"
        - "Job/Workspace:authenticated"
        - "Credentials/View:authenticated"
        - "Build Failure Analyzer/RemoveCause:authenticated"
        - "Build Failure Analyzer/UpdateCauses:authenticated"
        - "Build Failure Analyzer/ViewCauses:authenticated"
        - "Lockable Resources/Unlock:authenticated"
        - "Lockable Resources/Reserve:authenticated"
        - "SCM/Tag:authenticated"

  securityRealm:
    saml:
      binding: "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect"
      displayNameAttributeName: "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name"
      groupsAttributeName: "http://schemas.microsoft.com/ws/2008/06/identity/claims/groups"
      idpMetadataConfiguration:
        period: 15
        url: "https://login.microsoftonline.com/hmcts.net/FederationMetadata/2007-06/FederationMetadata.xml"
      maximumAuthenticationLifetime: 1209600
      usernameAttributeName: "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name"
      usernameCaseConversion: "none"

jobs:
  - url: https://raw.githubusercontent.com/hmcts/cnp-jenkins-config/master/jobdsl/organisations.groovy