jenkins:
  systemMessage: >-
    This jenkins is managed by configuration as code, update <a
    href="https://github.com/hmcts/cnp-jenkins-config/blob/master/cac-sandbox.yml">here</a>
  globalNodeProperties:
    - envVars:
        env:
          - key: INFRA_VAULT_NAME
            value: infra-vault-sandbox
          - key: NONPROD_ENVIRONMENT_NAME
            value: sandbox
          - key: NONPROD_SUBSCRIPTION_NAME
            value: sandbox
          - key: PROD_ENVIRONMENT_NAME
            value: sandbox
          - key: PREVIEW_ENVIRONMENT_NAME
            value: saat
          - key: PROD_SUBSCRIPTION_NAME
            value: sandbox
          - key: JAVA_OPTS
            value: -Xmx2g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
          - key: GRADLE_OPTS
            value: -Xmx2g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
          - key: SANDBOX_AKS_CLUSTER_NAME
            value: cnp-aks-sandbox-cluster
          - key: SANDBOX_AKS_RESOURCE_GROUP
            value: cnp-aks-sandbox-rg
  markupFormatter:
    rawHtml:
      disableSyntaxHighlighting: false
  numExecutors: 0
  primaryView:
    all:
      name: all
  views:
    - all:
        name: all
    - buildMonitor:
        includeRegex: >-
          HMCTS_Sandbox_DIV.+\/master
        name: DIV
        recurse: true
        title: Divorce Dashboard
  authorizationStrategy:
    globalMatrix:
      grantedPermissions:
#        - "Overall/Administer:authenticated" # Uncomment when testing locally / in test environment
        - "Overall/Administer:300e771f-856c-45cc-b899-40d78281e9c1"
        - "Overall/Read:authenticated"
        - "View/Create:authenticated"
        - "View/Read:authenticated"
        - "View/Configure:authenticated"
        - "View/Delete:authenticated"
        - "Agent/Create:authenticated"
        - "Agent/Build:authenticated"
        - "Agent/Connect:authenticated"
        - "Agent/Delete:authenticated"
        - "Agent/Configure:authenticated"
        - "Agent/Disconnect:authenticated"
        - "Run/Delete:authenticated"
        - "Run/Replay:authenticated"
        - "Run/Update:authenticated"
        - "Job/Configure:authenticated"
        - "Job/Cancel:authenticated"
        - "Job/Read:authenticated"
        - "Job/Build:authenticated"
        - "Job/Move:authenticated"
        - "Job/Discover:authenticated"
        - "Job/Discover:anonymous"
        - "Job/Create:authenticated"
        - "Job/Workspace:authenticated"
        - "Job/Delete:authenticated"
        - "Credentials/View:authenticated"
        - "Build Failure Analyzer/RemoveCause:authenticated"
        - "Build Failure Analyzer/UpdateCauses:authenticated"
        - "Build Failure Analyzer/ViewCauses:authenticated"
        - "Lockable Resources/Unlock:authenticated"
        - "Lockable Resources/Reserve:authenticated"
        - "SCM/Tag:authenticated"

  securityRealm:
    saml:
      binding: "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect"
      displayNameAttributeName: "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name"
      groupsAttributeName: "http://schemas.microsoft.com/ws/2008/06/identity/claims/groups"
      idpMetadataConfiguration:
        period: 15
        url: "https://login.microsoftonline.com/hmcts.net/FederationMetadata/2007-06/FederationMetadata.xml"
      maximumAuthenticationLifetime: 1209600
      usernameAttributeName: "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name"
      usernameCaseConversion: "none"
# uncomment when testing your own jenkins build / local testing (also uncomment admin:authenticated in grantedPermissions)
#  securityRealm:
#    local:
#      allowsSignup: false
#      users:
#        - id: "admin"
#          password: "admin"

jobs:
  - url: https://raw.githubusercontent.com/hmcts/cnp-jenkins-config/master/jobdsl/organisations.groovy

unclassified:
  location:
    adminAddress: jenkins-reform@hmcts.net
    url: 'https://sandbox-build.platform.hmcts.net'
  globalLibraries:
    libraries:
      - name: 'Infrastructure'
        includeInChangesets: false
        defaultVersion: master
        retriever:
          modernSCM:
            scm:
              github:
                credentialsId: jenkins-github-hmcts-api-token
                repoOwner: hmcts
                repository: cnp-jenkins-library
      - name: 'Pipeline'
        includeInChangesets: false
        defaultVersion: master
        retriever:
          modernSCM:
            scm:
              github:
                credentialsId: jenkins-github-hmcts-api-token
                repoOwner: hmcts
                repository: cnp-jenkins-library
  slackNotifier:
    teamDomain: hmcts-reform
    tokenCredentialId: slack-token
  githubpluginconfig:
    configs:
      - name: "GitHub"
        apiUrl: "https://api.github.com"
        credentialsId: "jenkins-github-hmcts-api-token"
        manageHooks: false
  azureKeyVault:
    keyVaultURL: https://infra-vault-sandbox.vault.azure.net
    credentialID: jenkinsServicePrincipal
  timestamperConfig:
    allPipelines: true
