jenkins:
  systemMessage: >-
    This jenkins is managed by configuration as code, update <a
    href="https://github.com/hmcts/cnp-jenkins-config/blob/master/cac-test.yml">here</a>
  globalNodeProperties:
    - envVars:
        env:
          - key: INFRA_VAULT_NAME
            value: infra-vault-sandbox
          - key: NONPROD_ENVIRONMENT_NAME
            value: saat
          - key: NONPROD_SUBSCRIPTION_NAME
            value: sandbox
          - key: PROD_ENVIRONMENT_NAME
            value: sprod
          - key: PROD_SUBSCRIPTION_NAME
            value: sandbox
          - key: JAVA_OPTS
            value: -Xmx2g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
          - key: GRADLE_OPTS
            value: -Xmx2g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
  Cloud:
    - azureVM:
        azureCredentialsId: "jenkinsServicePrincipal"
        cloudName: "cnp-azure1"
        deploymentTimeout: 1200
        existingResourceGroupName: "mgmt-vmimg-store-sandbox"
        maxVirtualMachinesLimit: 10
        resourceGroupReferenceType: "existing"
        vmTemplates:
          - agentLaunchMethod: "SSH"
            agentWorkspace: "/opt/jenkins"
            builtInImage: "Windows Server 2016"
            credentialsId: "vm_agent_creds"
            diskType: "managed"
            doNotUseMachineIfInitFails: true
            enableMSI: false
            executeInitScriptAsRoot: true
            existingStorageAccountName: "mgmtvmimgstoresandbox"
            imageReference:
              id: "/subscriptions/bf308a5c-0624-4334-8ff8-8dca9fd43783/resourceGroups/cnp-vmimages-sandbox/providers/Microsoft.Compute/images/moj-centos-agent74-20181113164555"
              version: "latest"
            imageTopLevelType: "advanced"
            initScript: |
              usermod -a -G docker jenkinsssh
              umount /mnt/resource
              mkdir -pv /opt/jenkins
              mount /dev/sdb1 /opt/jenkins
              chown -R jenkinsssh:jenkinsssh /opt/jenkins
              mv /tmp/jenkinsssh_id_rsa /home/jenkinsssh/.ssh/id_rsa
              chown jenkinsssh:jenkinsssh /home/jenkinsssh/.ssh/id_rsa
              chmod 0600 /home/jenkinsssh/.ssh/id_rsa
              mkdir /opt/jenkins/.gradle && echo 'org.gradle.daemon=false' > /opt/jenkins/.gradle/gradle.properties
              cat > /etc/dnsmasq.d/10-internal-forwarding<<EOF
              server=/#/10.99.196.9
              EOF
              systemctl restart dnsmasq
              cat > /etc/security/limits.d/30-jenkins.conf<<EOF
              jenkinsssh soft nofile 40960
              jenkinsssh hard nofile 40960
              jenkinsssh soft
              proc 32768
              jenkinsssh hard nproc 32768
              EOF
              ssh-keyscan github.com github.com >> /home/jenkinsssh/.ssh/known_hosts
              ssh-keygen -F github.com -f /home/jenkinsssh/.ssh/known_hosts # verifies key is correctly installed
            installDocker: false
            installGit: false
            installMaven: false
            jvmOptions: "-Xms4G -Xmx4G -XX:+UseG1GC -XX:+UseCompressedOops -XX:+UseCompressedClassPointers\
          \ -XX:+AlwaysPreTouch -XX:+UseStringDeduplication -XX:+ParallelRefProcEnabled\
          \ -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:+UnlockDiagnosticVMOptions\
          \ -XX:G1SummarizeRSetStatsPeriod=1"
            location: "UK South"
            noOfParallelJobs: 1
            osDiskSize: 0
            osType: "Linux"
            preInstallSsh: true
            retentionStrategy:
              azureVMCloudRetentionStrategy:
                idleTerminationMinutes: 60
            shutdownOnIdle: false
            storageAccountNameReferenceType: "existing"
            storageAccountType: "Standard_LRS"
            subnetName: "jenkins-subnet"
            templateDesc: "Jenkins build agents for HMCTS"
            templateDisabled: false
            templateName: "cnp-jenkins-builders"
            usageMode: "Use this node as much as possible"
            usePrivateIP: true
            virtualMachineSize: "Standard_D4_v3"
            virtualNetworkName: "mgmt-infra-sandbox"
            virtualNetworkResourceGroupName: "mgmt-infra-sandbox"
    - azureVM:
        azureCredentialsId: "jenkinsServicePrincipal"
        cloudName: "cnp-azure2"
        deploymentTimeout: 1200
        existingResourceGroupName: "mgmt-vmimg-store-sandbox"
        maxVirtualMachinesLimit: 10
        resourceGroupReferenceType: "existing"
        vmTemplates:
          - agentLaunchMethod: "SSH"
            agentWorkspace: "/opt/jenkins"
            builtInImage: "Windows Server 2016"
            credentialsId: "vm_agent_creds"
            diskType: "managed"
            doNotUseMachineIfInitFails: true
            enableMSI: false
            executeInitScriptAsRoot: true
            existingStorageAccountName: "mgmtvmimgstoresandbox"
            imageReference:
              id: "/subscriptions/bf308a5c-0624-4334-8ff8-8dca9fd43783/resourceGroups/cnp-vmimages-sandbox/providers/Microsoft.Compute/images/moj-centos-agent74-20181113164555"
              version: "latest"
            imageTopLevelType: "advanced"
            initScript: |
              usermod -a -G docker jenkinsssh
              umount /mnt/resource
              mkdir -pv /opt/jenkins
              mount /dev/sdb1 /opt/jenkins
              chown -R jenkinsssh:jenkinsssh /opt/jenkins
              mv /tmp/jenkinsssh_id_rsa /home/jenkinsssh/.ssh/id_rsa
              chown jenkinsssh:jenkinsssh /home/jenkinsssh/.ssh/id_rsa
              chmod 0600 /home/jenkinsssh/.ssh/id_rsa
              mkdir /opt/jenkins/.gradle && echo 'org.gradle.daemon=false' > /opt/jenkins/.gradle/gradle.properties
              cat > /etc/dnsmasq.d/10-internal-forwarding<<EOF
              server=/#/10.99.196.9
              EOF
              systemctl restart dnsmasq
              cat > /etc/security/limits.d/30-jenkins.conf<<EOF
              jenkinsssh soft nofile 40960
              jenkinsssh hard nofile 40960
              jenkinsssh soft
              proc 32768
              jenkinsssh hard nproc 32768
              EOF
              ssh-keyscan github.com github.com >> /home/jenkinsssh/.ssh/known_hosts
              ssh-keygen -F github.com -f /home/jenkinsssh/.ssh/known_hosts # verifies key is correctly installed
            installDocker: false
            installGit: false
            installMaven: false
            jvmOptions: "-Xms4G -Xmx4G -XX:+UseG1GC -XX:+UseCompressedOops -XX:+UseCompressedClassPointers\
          \ -XX:+AlwaysPreTouch -XX:+UseStringDeduplication -XX:+ParallelRefProcEnabled\
          \ -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:+UnlockDiagnosticVMOptions\
          \ -XX:G1SummarizeRSetStatsPeriod=1"
            location: "UK South"
            noOfParallelJobs: 1
            osDiskSize: 0
            osType: "Linux"
            preInstallSsh: true
            retentionStrategy:
              azureVMCloudRetentionStrategy:
                idleTerminationMinutes: 60
            shutdownOnIdle: false
            storageAccountNameReferenceType: "existing"
            storageAccountType: "Standard_LRS"
            subnetName: "jenkins-subnet"
            templateDesc: "Jenkins build agents for HMCTS"
            templateDisabled: false
            templateName: "cnp-jenkins-builders"
            usageMode: "Use this node as much as possible"
            usePrivateIP: true
            virtualMachineSize: "Standard_D4_v3"
            virtualNetworkName: "mgmt-infra-sandbox"
            virtualNetworkResourceGroupName: "mgmt-infra-sandbox"

  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: false
  markupFormatter:
    rawHtml:
      disableSyntaxHighlighting: false
  numExecutors: 0
  primaryView:
    all:
      name: all
  views:
    - all:
        name: all
  authorizationStrategy:
    globalMatrix:
      grantedPermissions:
        - "Overall/Administer:authenticated"
        - "Overall/Administer:300e771f-856c-45cc-b899-40d78281e9c1"
        - "Overall/Read:authenticated"
        - "View/Create:authenticated"
        - "View/Read:authenticated"
        - "View/Configure:authenticated"
        - "View/Delete:authenticated"
        - "Agent/Create:authenticated"
        - "Agent/Build:authenticated"
        - "Agent/Connect:authenticated"
        - "Agent/Delete:authenticated"
        - "Agent/Configure:authenticated"
        - "Agent/Disconnect:authenticated"
        - "Run/Delete:authenticated"
        - "Run/Replay:authenticated"
        - "Run/Update:authenticated"
        - "Job/Configure:authenticated"
        - "Job/Cancel:authenticated"
        - "Job/Read:authenticated"
        - "Job/Build:authenticated"
        - "Job/Move:authenticated"
        - "Job/Discover:authenticated"
        - "Job/Discover:anonymous"
        - "Job/Create:authenticated"
        - "Job/Workspace:authenticated"
        - "Job/Delete:authenticated"
        - "Credentials/View:authenticated"
        - "Build Failure Analyzer/RemoveCause:authenticated"
        - "Build Failure Analyzer/UpdateCauses:authenticated"
        - "Build Failure Analyzer/ViewCauses:authenticated"
        - "Lockable Resources/Unlock:authenticated"
        - "Lockable Resources/Reserve:authenticated"
        - "SCM/Tag:authenticated"
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          password: "admin"


unclassified:
  location:
    adminAddress: jenkins-reform@hmcts.net
    url: 'http://sandbox:8088'
  globalLibraries:
    libraries:
      - name: 'Infrastructure'
        includeInChangesets: false
        defaultVersion: master
        retriever:
          modernSCM:
            scm:
              github:
                credentialsId: jenkins-github-hmcts-api-token
                repoOwner: hmcts
                repository: cnp-jenkins-library
      - name: 'Pipeline'
        includeInChangesets: false
        defaultVersion: master
        retriever:
          modernSCM:
            scm:
              github:
                credentialsId: jenkins-github-hmcts-api-token
                repoOwner: hmcts
                repository: cnp-jenkins-library
  slackNotifier:
    teamDomain: hmcts-reform
    tokenCredentialId: slack-token
  githubpluginconfig:
    configs:
      - name: "GitHub"
        apiUrl: "https://api.github.com"
        credentialsId: "jenkins-github-hmcts-api-token"
        manageHooks: false
  azureKeyVault:
    keyVaultURL: https://infra-vault-sandbox.vault.azure.net
    credentialID: jenkinsServicePrincipal
  timestamperConfig:
    allPipelines: true
  # sonarglobalconfiguration:
  #   installations:
  #     - additionalAnalysisProperties: sonar.organization=hmcts
  #       name: SonarQube
  #       serverAuthenticationToken: '${SONARCLOUD}'
  #       serverUrl: 'https://sonarcloud.io'

#credentials:
#  system:
#    domainCredentials:
#      - credentials:
#          - usernamePassword:
#              scope: GLOBAL
#              id: jenkins-github-hmcts-api-token
#              username: jenkins-reform-cnp
#              password: '${JENKINS_REFORM_CNP}'
#              description: CNP jenkins apo token
#          - string:
#              scope: GLOBAL
#              id: slack-token
#              secret: '${SLACK_TOKEN}'
#              description: Slack token

jobs:
  - url: https://raw.githubusercontent.com/hmcts/cnp-jenkins-config/master/jobdsl/organisations-cnptest.groovy
#  - file:  '/usr/share/jenkins/jobdsl/organisations.groovy'