helm:
  java:
    - version: "4.0.13"
      date_deadline: "2023-03-29"
  nodejs:
    - version: "2.4.14"
      date_deadline: "2023-03-29"
  job:
    - version: "1.0.0"
      date_deadline: "2023-05-31"
  blobstorage:
    - version: "1.0.1"
      date_deadline: "2023-08-13"
  servicebus:
    - version: "1.0.4"
      date_deadline: "2023-08-13"
  ccd:
    - version: "8.0.27"
      date_deadline: "2023-03-29"
  elasticsearch:
    - version: "7.17.3"
      date_deadline: "2023-03-29"
gradle:
  java-logging:
    - version: "6.0.5"
      date_deadline: "2023-03-01"
