helm:
  java:
    - version: "5.0.0"
      date_deadline: "2023-10-23"
  nodejs:
    - version: "3.0.0"
      date_deadline: "2023-10-23"
  job:
    - version: "2.1.1"
      date_deadline: "2024-01-24"
  function:
    - version: "2.4.1"
      date_deadline: "2023-10-23"
  base:
    - version: "1.1.0"
      date_deadline: "2023-10-23"
  blobstorage:
    - version: "1.0.1"
      date_deadline: "2023-08-13"
  servicebus:
    - version: "1.0.4"
      date_deadline: "2023-08-13"
  ccd:
    - version: "8.0.27"
      date_deadline: "2023-03-29"
  elasticsearch:
    - version: "7.17.3"
      date_deadline: "2023-03-29"
gradle:
  java-logging:
    - version: "6.0.1"
      date_deadline: "2023-10-28"
npm:
  angular/core:
    - version: "16"
      date_deadline: ""
