---

jenkins_external_url: 'https://build.platform.hmcts.net'

vault_uri: 'https://infra-vault-prod.vault.azure.net/'

login_security_enabled: 'true'

build_failure_analyzer_hostname: 'build-failure-analyzer.platform.hmcts.net'

api_key_username_cdm: 'jenkins-reform-cdm'
