---

# Needed so that jenkins can ssh/cli connect to itself with vanity hostname
# otherwise e.g. build.reform.hmcts.net - the ssh cli tries to connect to the proxy
- name: "Add jenkins_hostname to hosts file"
  lineinfile:
    path: /etc/hosts
    line: "127.0.0.1 {{ jenkins_hostname}} # ansible jenkins role added"
    state: present
  # this fails in docker
  failed_when: false
